EcommerceWeb/Controllers/HomeController.cs
using EcommerceWeb.DAL;
using EcommerceWeb.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EcommerceWeb.Controllers
{
    public class HomeController : Controller
    {
        private EcommerceContext db = new EcommerceContext();
        public ActionResult Index()
        {
            return View(db.MatHangs.ToList());
        }

        [HttpPost]
        public ActionResult Index(string product)
        {
            EcommerceContext entities = new EcommerceContext();
            return View(entities.MatHangs.Where(x => x.TenMH.Contains(product.ToLower())).ToList());
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Search()
        {
            return View(db.MatHangs.ToList());
        }

        public ActionResult Man(int page = 1, int pageSize = 8)
        {
            List<MatHang> products = db.MatHangs.Where(x => x.Gender == 1).ToList();
            PagedList<MatHang> model = new PagedList<MatHang>(products, page, pageSize);
            return View(model);
        }
        public ActionResult Woman(int page = 1, int pageSize = 8)
        {
            List<MatHang> products = db.MatHangs.Where(x => x.Gender == 0).ToList();
            PagedList<MatHang> model = new PagedList<MatHang>(products, page, pageSize);
            return View(model);
        }
    }
}

EcommerceWeb/Controllers/MatHangController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using PagedList;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EcommerceWeb.DAL;
using EcommerceWeb.Models;
using System.IO;

namespace EcommerceWeb.Controllers
{
    public class MatHangController : Controller
    {
        private EcommerceContext db = new EcommerceContext();

        // GET: MatHang
        public ActionResult Index()
        {
            var matHangs = db.MatHangs.Include(m => m.LoaiHang);

            return View(matHangs.ToList());
        }

        // GET: MatHang/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MatHang matHang = db.MatHangs.Find(id);
            if (matHang == null)
            {
                return HttpNotFound();
            }

            var commentList = db.DanhGias.Where(cmt => cmt.MatHangID == id).ToList();

            var tupleResult = new Tuple<MatHang, List<DanhGia>>(matHang, commentList);
             
            return View(tupleResult);
        }

        // GET: MatHang/Create
        public ActionResult Create()
        {
            ViewBag.LoaiID = new SelectList(db.LoaiHangs, "LoaiID", "TenLoai");
            return View();
        }

        // POST: MatHang/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HttpPostedFileBase file, [Bind(Include = "MatHangID,TenMH,DonGia,MoTa,LoaiID,NSX,HSD,TongSoLuong")] MatHang matHang)
        {
            if (ModelState.IsValid)
            {
                var allowedExtensions = new[] { ".Jpg", ".png", ".jpg", "jpeg" };
                var ext = Path.GetExtension(file.FileName);

                if (allowedExtensions.Contains(ext)) //check what type of extension
                {
                    var path = Path.Combine(Server.MapPath("~/image"), Path.GetFileName(file.FileName));
                    var imgLink = "~/image/" + file.FileName;
                    matHang.HinhAnh = imgLink;
                    matHang.SoLuongTonKho = matHang.TongSoLuong;
                    db.MatHangs.Add(matHang);
                    ViewBag.FileStatus = "File uploaded successfully.";
                    db.SaveChanges();
                    file.SaveAs(path);
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.message = "Please choose only Image file";
                }
            }

            ViewBag.LoaiID = new SelectList(db.LoaiHangs, "LoaiID", "TenLoai", matHang.LoaiID);
            return View(matHang);
        }


        // GET: MatHang/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MatHang matHang = db.MatHangs.Find(id);
            if (matHang == null)
            {
                return HttpNotFound();
            }
            ViewBag.LoaiID = new SelectList(db.LoaiHangs, "LoaiID", "TenLoai", matHang.LoaiID);
            return View(matHang);
        }

        // POST: MatHang/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MatHangID,TenMH,DonGia,MoTa,Size,Color,Gender,LoaiID,HinhAnh")] MatHang matHang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(matHang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LoaiID = new SelectList(db.LoaiHangs, "LoaiID", "TenLoai", matHang.LoaiID);
            return View(matHang);
        }

        // GET: MatHang/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MatHang matHang = db.MatHangs.Find(id);
            if (matHang == null)
            {
                return HttpNotFound();
            }
            return View(matHang);
        }

        // POST: MatHang/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MatHang matHang = db.MatHangs.Find(id);
            db.MatHangs.Remove(matHang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EcommerceWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

EcommerceWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "About ARON";
}


<div style="text-align:center; margin-top: 60px; margin-left:60px; margin-right:60px">
    <h2>@ViewBag.Title</h2>
    <div style="margin-top: 30px;margin-bottom:60px">
        <img src="~/image/about_pg.png" />
    </div>
    <div class="content-area">
        <div class="gucci-wysiwyg-content">
            <p class="times-14" style="text-align: justify;">
                Influential, innovative and progressive, ARON is reinventing a wholly modern approach to fashion. Under the new vision of creative director Alessandro Michele,
                the House has redefined luxury for the 21st century, further reinforcing its position as one of the world’s most desirable fashion houses. Eclectic, contemporary,
                romantic—ARON products represent the pinnacle of Italian craftsmanship and are unsurpassed for their quality and attention to detail.
                <br>
                <br>
                ARON is part of the Kering Group. A global Luxury group, Kering manages the development of a series of renowned Houses in Fashion, Leather Goods, Jewellery and Watches.
                <br>
                <br>
                Discover the stories behind Alessandro Michele's collections, exclusively on <a href="#" style="color: #C1B497;"><u>Stories</u></a>
            </p>
        </div>
    </div>
</div>

EcommerceWeb/Views/Home/Man.cshtml
@using System.Globalization;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    CultureInfo cul = CultureInfo.GetCultureInfo("vi-VN");
}
@model PagedList.IPagedList<EcommerceWeb.Models.MatHang>
@using PagedList.Mvc;

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link rel="stylesheet"
          href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <style>
        div.gallery img {
            width: 150px;
            height: 150px;
            margin: 30px;
            display: inline-block;
        }

        .zoomPic:hover {
            transform: scale(1.5);
            transition: transform .2s;
        }

        div.gallery {
            margin: 30px;
            /*border: 2px solid #ccc;*/
            width: auto;
            height: auto;
            display: inline-block;
            background-color: #E7E7E7;
        }


        .pagination > li > a {
            background-color: white;
            color: #5A4181;
        }

            .pagination > li > a:focus,
            .pagination > li > a:hover,
            .pagination > li > span:focus,
            .pagination > li > span:hover {
                color: #5a5a5a;
                background-color: #eee;
                border-color: #ddd;
            }

        .pagination > .active > a {
            color: white;
            background-color: black !Important;
            border: solid 1px black !Important;
        }

            .pagination > .active > a:hover {
                background-color: black !Important;
                border: solid 1px black;
            }

        #buttonCart {
            color: black;
            border-radius: 0px;
            background: transparent;
            border: solid 2px;
            font-weight: bold;
        }

        .TwoButton {
            transition: .4s ease;
            opacity: 0;
            position: absolute;
            top: 65%;
            left: 50%;
            transform: translate(-50%, -50%);
            -ms-transform: translate(-50%, -50%);
            text-align: center;
        }

        .col-md-3:hover .TwoButton {
            opacity: 1;
        }
    </style>
</head>
<body>

    <div class="container-fluid" style="margin-top: 20px;">
        <div class="container">
            <img src="~/image/woman-banner.jpg" width="100%">
        </div>
        <div style="text-align:center; margin-top: 60px">
            <h2>for MAN</h2>
            <div class="row" style="margin-top: 50px">
                @foreach (var item in Model)
                {
                <div id="proItem" class="col-md-3">
                    <div class="gallery">
                        <a href="@Url.Action("Details","MatHang", new { id= item.MatHangID})">
                            <img class="zoomPic" src="@Url.Content(item.HinhAnh)" alt="ảnh lỗi rồi">
                        </a>
                    </div>
                    <div class="TwoButton">
                        <a href="/ShoppingCart/AddtoCart/@item.MatHangID" id="buttonCart" class="btn btn-primary btn-sm active" type="button" aria-pressed="true">Add To Cart</a>                        
                    </div>
                    <p style="font-weight: bold">@item.TenMH</p>
                    <p>$ @item.DonGia.ToString("#,###", @cul.NumberFormat)</p>
                </div>
                }
            </div>
        </div>
        <br />
        <div class="text-center">
            @Html.PagedListPager(Model, page => Url.Action("Man", new { page, pageSize = Model.PageSize }))
        </div>
    </div>

</body>
</html>

EcommerceWeb/Views/Home/Search.cshtml
@model IEnumerable<EcommerceWeb.Models.MatHang>
@using System.Globalization;
@{
    CultureInfo cul = CultureInfo.GetCultureInfo("vi-VN");
    Layout = "~/Views/Shared/SearchLayout.cshtml";
}
<!DOCTYPE html>
<html>
<head>
    <style>
        div.gallery img {
            width: 150px;
            height: 150px;
            margin: 30px;
            display: inline-block;
        }

        .zoomPic:hover {
            transform: scale(1.5);
            transition: transform .2s;
        }

        div.gallery {
            margin: 30px;
            /*border: 2px solid #ccc;*/
            width: auto;
            height: auto;
            display: inline-block;
            background-color: #E7E7E7;
        }

        #buttonCart {
            color: black;
            border-radius: 0px;
            background: transparent;
            border: solid 2px;
            font-weight: bold;
        }

        .TwoButton {
            transition: .4s ease;
            opacity: 0;
            position: absolute;
            top: 65%;
            left: 50%;
            transform: translate(-50%, -50%);
            -ms-transform: translate(-50%, -50%);
            text-align: center;
        }

        .col-md-3:hover .TwoButton {
            opacity: 1;
        }
    </style>
</head>
<body>
    <div style="text-align: center; margin-top: 100px">
        <div class="form-group">
            <div class="input-group" style="margin: 0 auto; width: 250px;">
                <span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>
                <input type="text" id="Search" placeholder="Search here..." class="form-control" />
            </div>
        </div>
    </div>

    <div style="text-align: center; margin: 10px">
        <div class="form-group">
            <div class="btn-group" id="btn-group">
                <button style="color: black" type="button" class="btn active" id="all">All</button>
                <button style="color: black" type="button" class="btn" id="burger">Burger</button>
                <button style="color: black" type="button" class="btn" id="pizza">Pizza</button>
                <button style="color: black" type="button" class="btn" id="pasta">Pasta</button>
                <button style="color: black" type="button" class="btn" id="fries">Fries</button>
            </div>
        </div>
    </div>

    <div style="text-align:center; margin-top: 60px">
        <div class="row" style="margin-top: 50px">
            @foreach (var item in Model)
            {
                <div id="proItem" class="col-md-3">
                    <div class="gallery">
                        <a href="@Url.Action("Details","MatHang", new { id= item.MatHangID})">
                            <img class="zoomPic" src="@Url.Content(item.HinhAnh)" alt="ảnh lỗi rồi">
                        </a>
                    </div>
                    <div class="TwoButton">
                        <a href="/ShoppingCart/AddtoCart/@item.MatHangID" id="buttonCart" class="btn btn-primary btn-sm active" type="button" aria-pressed="true">Add To Cart</a>
                    </div>
                    <p>@item.TenMH</p>
                    <p>$ @item.DonGia.ToString("#,###", @cul.NumberFormat)</p>
                </div>
            }
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            function Contains(text_one, text_two) {
                if (text_one.indexOf(text_two) != -1) return true;
            }
            $("#Search").keyup(function () {
                var searchText = $("#Search").val().toLowerCase();
                $(".col-md-3").each(function () {
                    if (!Contains($(this).text().toLowerCase(), searchText)) {
                        $(this).hide();
                    } else {
                        $(this).show();
                    }
                })
            })
            $("#burger").click(function () {
                $('.btn').removeClass('active');
                $(this).addClass('active');
                $(".col-md-3").each(function () {
                    if (!Contains($(this).text(), "Burger")) {
                        $(this).hide();
                    } else {
                        $(this).show();
                    }
                })
            })
            $("#pizza").click(function () {
                $('.btn').removeClass('active');
                $(this).addClass('active');
                $(".col-md-3").each(function () {
                    if (!Contains($(this).text(), "Pizza")) {
                        $(this).hide();
                    } else {
                        $(this).show();
                    }
                })
            })
            $("#pasta").click(function () {
                $('.btn').removeClass('active');
                $(this).addClass('active');
                $(".col-md-3").each(function () {
                    if (!Contains($(this).text(), "Pasta")) {
                        $(this).hide();
                    } else {
                        $(this).show();
                    }
                })
            })
            $("#fries").click(function () {
                $('.btn').removeClass('active');
                $(this).addClass('active');
                $(".col-md-3").each(function () {
                    if (!Contains($(this).text(), "Fries")) {
                        $(this).hide();
                    } else {
                        $(this).show();
                    }
                })
            })
            $("#all").click(function () {
                $('.btn').removeClass('active');
                $(this).addClass('active');
                $(".col-md-3").each(function () {
                    if (!Contains($(this).text(), "")) {
                        $(this).hide();
                    } else {
                        $(this).show();
                    }
                })
            })
        })
    </script>
</body>
</html>

EcommerceWeb/Views/Home/Woman.cshtml
@using System.Globalization;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    CultureInfo cul = CultureInfo.GetCultureInfo("vi-VN");
}
@model PagedList.IPagedList<EcommerceWeb.Models.MatHang>
@using PagedList.Mvc;

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link rel="stylesheet"
          href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <style>
        div.gallery img {
            width: 150px;
            height: 150px;
            margin: 30px;
            display: inline-block;
        }

        .zoomPic:hover {
            transform: scale(1.5);
            transition: transform .2s;
        }

        div.gallery {
            margin: 30px;
            /*border: 2px solid #ccc;*/
            width: auto;
            height: auto;
            display: inline-block;
            background-color: #E7E7E7;
        }

        .pagination > li > a {
            background-color: white;
            color: #5A4181;
        }

            .pagination > li > a:focus,
            .pagination > li > a:hover,
            .pagination > li > span:focus,
            .pagination > li > span:hover {
                color: #5a5a5a;
                background-color: #eee;
                border-color: #ddd;
            }

        .pagination > .active > a {
            color: white;
            background-color: black !Important;
            border: solid 1px black !Important;
        }

            .pagination > .active > a:hover {
                background-color: black !Important;
                border: solid 1px black;
            }

        #buttonCart {
            color: black;
            border-radius: 0px;
            background: transparent;
            border: solid 2px;
            font-weight: bold;
        }

        .TwoButton {
            transition: .4s ease;
            opacity: 0;
            position: absolute;
            top: 65%;
            left: 50%;
            transform: translate(-50%, -50%);
            -ms-transform: translate(-50%, -50%);
            text-align: center;
        }

        .col-md-3:hover .TwoButton {
            opacity: 1;
        }
    </style>
</head>
<body>

    <div class="container-fluid" style="margin-top: 20px;">
        <div class="container">
            <img src="~/image/woman-banner.jpg" width="100%">
        </div>
        <div style="text-align:center; margin-top: 60px">
            <h2>for WOMAN</h2>
            <div class="row" style="margin-top: 50px">
                @foreach (var item in Model)
                {
                <div id="proItem" class="col-md-3">
                    <div class="gallery">
                        <a href="@Url.Action("Details","MatHang", new { id= item.MatHangID})">
                            <img class="zoomPic" src="@Url.Content(item.HinhAnh)" alt="ảnh lỗi rồi">
                        </a>
                    </div>
                    <div class="TwoButton">
                        <a href="/ShoppingCart/AddtoCart/@item.MatHangID" id="buttonCart" class="btn btn-primary btn-sm active" type="button" aria-pressed="true">Add To Cart</a>
                    </div>
                    <p style="font-weight: bold">@item.TenMH</p>
                    <p>$ @item.DonGia.ToString("#,###", @cul.NumberFormat)</p>
                </div>
                }
            </div>
        </div>
        <br />
        <div class="text-center">
            @Html.PagedListPager(Model, page => Url.Action("Woman", new { page, pageSize = Model.PageSize }))
        </div>
    </div>

</body>
</html>