EcommerceWeb/Models/DanhGia.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System;

namespace EcommerceWeb.Models
{
    public class DanhGia
    {
        static DanhGia instance;

        private static object locker = new object();
        public static DanhGia GetCart()
        {
            if (instance == null)
            {
                lock (locker)
                {
                    if (instance == null)
                    {
                        instance = new DanhGia();
                    }
                }
            }
            return instance;
        }

        public DanhGia(){}

        [Key]
        public int DanhGiaID { get; set; }

        public string NoiDung { get; set; }

        public int Sao { get; set; }

        public DateTime ThoiGian { get; set; }

        public DateTime LanCuoiChinhSua { get; set; }

        public int KhachHangID { get; set; }
        [ForeignKey("KhachHangID")]
        public virtual KhachHang KhachHang { get; set; }

        public int MatHangID { get; set; }
        [ForeignKey("MatHangID")]
        public virtual MatHang MatHang { get; set; }
    }
}

EcommerceWeb/Controllers/DanhGiaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EcommerceWeb.DAL;
using EcommerceWeb.Models;

namespace EcommerceWeb.Controllers
{
    public class DanhGiaController : Controller
    {
        private EcommerceContext db = new EcommerceContext();

        // GET: DanhGias
        public ActionResult Index()
        {
            var danhGias = db.DanhGias.Include(d => d.KhachHang).Include(d => d.MatHang);
            return View(danhGias.ToList());
        }

        // GET: DanhGias/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DanhGia danhGia = db.DanhGias.Find(id);
            if (danhGia == null)
            {
                return HttpNotFound();
            }
            return View(danhGia);
        }

        // GET: DanhGias/Create
        public ActionResult Create()
        {
            ViewBag.KhachHangID = new SelectList(db.KhachHangs, "KhachHangID", "TenKH");
            ViewBag.MatHangID = new SelectList(db.MatHangs, "MatHangID", "TenMH");
            return View();
        }

        // POST: DanhGias/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "NoiDung,Sao,KhachHangID,MatHangID")] DanhGia danhGia)
        {
            if (ModelState.IsValid)
            {
                danhGia.ThoiGian = DateTime.Now;
                danhGia.LanCuoiChinhSua = DateTime.Now;
                db.DanhGias.Add(danhGia);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.KhachHangID = new SelectList(db.KhachHangs, "KhachHangID", "TenKH", danhGia.KhachHangID);
            ViewBag.MatHangID = new SelectList(db.MatHangs, "MatHangID", "TenMH", danhGia.MatHangID);
            return View(danhGia);
        }

        // GET: DanhGias/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DanhGia danhGia = db.DanhGias.Find(id);
            if (danhGia == null)
            {
                return HttpNotFound();
            }
            ViewBag.KhachHangID = new SelectList(db.KhachHangs, "KhachHangID", "TenKH", danhGia.KhachHangID);
            ViewBag.MatHangID = new SelectList(db.MatHangs, "MatHangID", "TenMH", danhGia.MatHangID);
            return View(danhGia);
        }

        // POST: DanhGias/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "NoiDung,Sao,LanCuoiChinhSua,KhachHangID,MatHangID")] DanhGia danhGia)
        {
            if (ModelState.IsValid)
            {
                danhGia.LanCuoiChinhSua = DateTime.Now;
                db.Entry(danhGia).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.KhachHangID = new SelectList(db.KhachHangs, "KhachHangID", "TenKH", danhGia.KhachHangID);
            ViewBag.MatHangID = new SelectList(db.MatHangs, "MatHangID", "TenMH", danhGia.MatHangID);
            return View(danhGia);
        }

        // GET: DanhGias/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DanhGia danhGia = db.DanhGias.Find(id);
            if (danhGia == null)
            {
                return HttpNotFound();
            }
            return View(danhGia);
        }

        // POST: DanhGias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DanhGia danhGia = db.DanhGias.Find(id);
            db.DanhGias.Remove(danhGia);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        
        public int totalDanhGiaByProductId(int productId)
        {
            if (productId.Equals(null))
            {
                return 0;
            }
            return db.DanhGias.Where(cmt => cmt.MatHangID.Equals(productId)).ToList().Count;
        }

        public List<DanhGia> getDanhGiaByUserId(int userId)
        {
            if (userId.Equals(null))
            {
                return new List<DanhGia>();
            }
            return db.DanhGias.Where(cmt => cmt.MatHangID.Equals(userId)).ToList();
        }
    }
}

EcommerceWeb/Views/DanhGias/Create.cshtml
@model EcommerceWeb.Models.DanhGia

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "DanhGia", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DanhGia</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NoiDung, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoiDung, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThoiGian, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ThoiGian, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ThoiGian, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LanCuoiChinhSua, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LanCuoiChinhSua, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LanCuoiChinhSua, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KhachHangID, "KhachHangID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("KhachHangID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.KhachHangID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MatHangID, "MatHangID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MatHangID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MatHangID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EcommerceWeb/Views/DanhGias/Delete.cshtml
@model EcommerceWeb.Models.DanhGia

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DanhGia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.KhachHang.TenKH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KhachHang.TenKH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MatHang.TenMH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MatHang.TenMH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoiDung)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoiDung)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThoiGian)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThoiGian)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LanCuoiChinhSua)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LanCuoiChinhSua)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EcommerceWeb/Views/DanhGias/Details.cshtml
@model EcommerceWeb.Models.DanhGia

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>DanhGia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.KhachHang.TenKH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KhachHang.TenKH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MatHang.TenMH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MatHang.TenMH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoiDung)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoiDung)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThoiGian)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThoiGian)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LanCuoiChinhSua)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LanCuoiChinhSua)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.DanhGiaID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

EcommerceWeb/Views/DanhGias/Edit.cshtml
@model EcommerceWeb.Models.DanhGia

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DanhGia</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DanhGiaID)

        <div class="form-group">
            @Html.LabelFor(model => model.NoiDung, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoiDung, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThoiGian, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ThoiGian, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ThoiGian, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LanCuoiChinhSua, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LanCuoiChinhSua, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LanCuoiChinhSua, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KhachHangID, "KhachHangID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("KhachHangID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.KhachHangID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MatHangID, "MatHangID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MatHangID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MatHangID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EcommerceWeb/Views/DanhGias/Index.cshtml
@model IEnumerable<EcommerceWeb.Models.DanhGia>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.KhachHang.TenKH)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MatHang.TenMH)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NoiDung)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ThoiGian)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LanCuoiChinhSua)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.KhachHang.TenKH)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MatHang.TenMH)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NoiDung)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ThoiGian)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LanCuoiChinhSua)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.DanhGiaID }) |
            @Html.ActionLink("Details", "Details", new { id=item.DanhGiaID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.DanhGiaID })
        </td>
    </tr>
}

</table>